[package]
name = "format"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
byteorder = "1"
aes = "0.8"
openssl-sys = "0.9.83"
openssl = { version = "0.10", features = ["vendored"] }
oodle-safe = "0.1.0"
