[package]
name = "format"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
bytemuck = "1"
byteorder = "1"
aes = "0.8"
oodle-safe = "0.1.0"
rayon = "1"
rug = "1.24"

# TODO: PEM decoding is broken in the latest relases?
pkcs1 = { version = "0.3", features = ["std", "pem", "alloc"] }

[dependencies.thiserror]
workspace = true
