[package]
name = "fstools"
edition = "2021"

[dependencies]
format = { path = "format" }
souls_vfs = { path = "vfs" }

[dev-dependencies]
insta = "1"
libtest-mimic = "0.7"

[[test]]
name = "dcx"
path = "tests/dcx.rs"
harness = false

[workspace]
resolver = "2"
default-members = ["cli", "viewer"]
members = [
    "format",
    "cli",
    "viewer",
    "vfs",
    "util",
]

[workspace.package]
version = "0.1.0"
license = "MIT AND Apache-2.0"

[workspace.dependencies.thiserror]
version = "1"