[package]
name = "fstools"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
fstools_formats.workspace = true
fstools_vfs.workspace = true

[dev-dependencies]
insta = "1"
libtest-mimic = "0.7"

[[test]]
name = "dcx"
path = "tests/dcx.rs"
harness = false

[workspace]
resolver = "2"
default-members = ["crates/cli", "crates/viewer"]
members = [
    "crates/formats",
    "crates/cli",
    "crates/viewer",
    "crates/vfs",
]

[workspace.package]
version = "0.1.0"
license = "MIT AND Apache-2.0"
edition = "2021"

[workspace.dependencies]
fstools_formats = { path = "crates/formats", version = "0.1.0" }
fstools_vfs = { path = "crates/vfs", version = "0.1.0" }
memmap2 = "0.7"
rayon = "1"
thiserror = "1"