[package]
name = "util"
version.workspace = true
license.workspace = true
edition = "2021"

[dependencies]
format = { path = "../format" }
byteorder = "1"
souls_vfs = { path = "../vfs" }

[dependencies.thiserror]
workspace = true