[package]
name = "viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
byteorder = "1"
bevy = { version = "0.12", features = ["dds"] }
bevy-inspector-egui = "0.22.1"
format = { path = "../format" }
util = { path = "../util" }
bevy_panorbit_camera = "0.13"
