[package]
name = "fstools_elden_ring_support"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
fstools.workspace = true